# Generated by Django 5.1.2 on 2026-07-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
