# Generated by Django 5.1.2 on 2026-07-22 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipo_capitan'),
        ('jugadores', '0002_alter_jugador_edad_alter_jugador_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['equipo__nombre', 'numero', 'apellidos']},
        ),
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='numero',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('equipo', 'numero'), name='numero_unico_por_equipo'),
        ),
    ]
