# Generated by Django 5.1.2 on 2026-07-21 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0003_partido'),
        ('jugadores', '0002_alter_jugador_edad_alter_jugador_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='info.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMARILLA', 'Amarilla'), ('ROJA', 'Roja')], max_length=10)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='info.partido')),
            ],
        ),
    ]
