# Generated by Django 5.1.2 on 2026-07-22 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gol',
            options={'ordering': ['partido', 'minuto'], 'verbose_name': 'Gol', 'verbose_name_plural': 'Goles'},
        ),
        migrations.AlterField(
            model_name='gol',
            name='minuto',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(130)]),
        ),
    ]
