# Generated by Django 5.1.2 on 2026-07-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='capitan',
        ),
    ]
