# Generated by Django 5.1.2 on 2026-07-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='fase',
            field=models.CharField(choices=[('REGULAR', 'Fase Regular'), ('CUARTOS', 'Cuartos de Final'), ('SEMIS', 'Semifinal'), ('FINAL', 'Final')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
