# Generated by Django 5.1.2 on 2026-07-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipo_capitan'),
        ('info', '0003_partido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['jornada__numero', 'fecha', 'hora'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.RemoveField(
            model_name='jornada',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='jornada',
            name='fecha_inicio',
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.UniqueConstraint(fields=('jornada', 'equipo_local', 'equipo_visitante'), name='partido_unico_por_jornada'),
        ),
    ]
