# Generated by Django 5.1.2 on 2026-07-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_jornada_options_alter_partido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
